version : "3.9"
services :
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend_prod:local
    volumes:
      - front:/app/build
    networks:
      - pongnet
    init: true
    restart: always

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - pongnet
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend_prod:local
    networks:
      - pongnet
    depends_on: 
      - database
    restart: always
    ports:
      - 3001:3001
      - 3004:3004
    init : true
    restart: always
    
  nginx :
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx_prod:local
    networks:
      - pongnet
    volumes :
      - front:/var/www/html/
    depends_on:
      - backend
    ports:
      - 8000:80
    init: true
    restart: always

  migration:
    build:
      context: ./backend/code/prisma
      dockerfile: Dockerfile
    image: prisma_migration:local
    networks:
      - pongnet
    depends_on:
      - backend
   
volumes: 
  front:
  database:

networks:
  pongnet:
  
